name: pgog
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2020.1.1
  - certifi=2019.11.28
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - ncurses=6.2
  - openssl=1.1.1d
  - pip=20.0.2
  - python=3.6.10
  - readline=7.0
  - setuptools=45.2.0
  - sqlite=3.31.1
  - tk=8.6.8
  - wheel=0.34.2
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - absl-py==0.9.0
    - astor==0.8.1
    - bleach==1.5.0
    - cffi==1.14.0
    - chardet==3.0.4
    - cryptography==2.8
    - decorator==4.4.2
    - gast==0.3.3
    - grpcio==1.27.2
    - h5py==2.10.0
    - html5lib==0.9999999
    - idna==2.9
    - imageio==2.8.0
    - imageio-ffmpeg==0.4.1
    - lmdb==0.98
    - markdown==3.2.1
    - moviepy==1.0.1
    - numpy==1.18.1
    - opencv-python==4.2.0.32
    - pillow==7.0.0
    - proglog==0.1.9
    - protobuf==3.11.3
    - pycparser==2.19
    - requests==2.23.0
    - scipy==1.4.1
    - six==1.14.0
    - tensorboard==1.6.0
    - tensorflow-gpu==1.6.0
    - termcolor==1.1.0
    - tqdm==4.43.0
    - urllib3==1.25.8
    - werkzeug==1.0.0

